<?php require('Template/header.phtml');?>
<div class="container">
    <div class="row justify-content-md-center">

                <div class="col-md-5 mt-2 mr-2 ">
                            <h5 class="text-center"> All Auctions </h5>
                            <table class="table table-striped table-dark">
                                <tr>
                                    <th> Auction ID</th>
                                    <th> Start Date </th>
                                    <th> End Date</th>
                                </tr>
                                <?php
                                //data gets all of the auctions
                                $data = getAllCurrentAuctions();
                                //live auction is the current date
                                $liveAuction = date("Y-m-d");
                                //future auctions gets the next day of today=
                                $futureAuctions = date('Y-m-d', strtotime('+1 day', strtotime($liveAuction)));
                                //for every date print out a row in the table
                                foreach ($data as $date)
                                {
                                    $id = $date->getID();
                                    $startDate = $date->getStartDate();
                                    $endDate = $date->getEndDate();
                                    //if the date is the same as the current date then produce a row stating its the current auction
                                    if($startDate == $liveAuction)
                                    {
                                        echo '
                                        <tr>
                                            <th style="color: red"> Current Auction &#x1F534 <div class="circle red"></div> </th>
                                            <th></th>
                                            <th></th>
                                        </tr>';
                                    }
                                    //if the date is the same as the current date+! then produce a row stating their future auctions
                                    if($startDate == $futureAuctions)
                                    {
                                        echo '
                                        <tr>
                                            <th style="color: green"> Future Auctions  </th>
                                            <th></th>
                                            <th></th>
                                        </tr>';
                                    }
                                    echo '<tr>';
                                    echo '<td>  '. $id.' </td>';
                                    echo '<td> '. $startDate.' </td>';
                                    echo '<td> '.  $endDate.' </td>';
                                    echo '<tr>';
                                }
                                ;?>
                            </table>
                            <h5 class="text-center"><button class=" btn btn-custom" name="auction-delete" type="button" data-toggle="modal" data-target="#exampleModal"> Delete An Auction </button></h5>
                            <?php
                            //if the delete button is pressed and an invalid entry has been given produce a display message else show a succes message
                            if($view->DeleteError == true)
                            {
                                echo '<div class="alert alert-danger text-center" role="alert">
                                 <i class="fa fa-exclamation-circle"> Please give a valid ID, refer to the table for valid IDs   </i>
                                </div>';
                            }
                            else if($view->successMessage)
                            {
                                echo '<div class="alert alert-success text-center" role="alert">
                                 <i class="fa fa-exclamation-circle"> Successfully Deleted Auction   </i>
                                </div>';
                            }
                            ?>
                </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body text-center">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h5 class="modal-title" id="exampleModalLabel text-center">Delete Confirmation</h5>
                        <p> Enter the Auction ID of the ID you want delete </p>
                        <form action="auctions.php" method="post">
                            <input class="mb-2" name="auctionID" type="number">
                            <br>
                            <button type="submit" class="btn  rounded-pill btn-custom" data-dismiss="modal"> <strong> No </strong> </button>
                            <button type="submit" class="btn  rounded-pill btn-custom" name="delete"><strong> Yes </strong></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5 mt-2 mr-2">
            <h5 class="text-center"> Add Auction </h5>
            <div class="card mb-4 box-shadow" style="background: #2c3034; color: white">
                <div class="card-title">
                    <h1 class="text-center"> Available Auction Dates </h1>
                </div>
                <div class="card-body">
                    <p class="card-text"> Here is a list of available start dates for auctions, these auctions start dates will be upto a week later then the last current auction</p>
                    <form method="post" action="auctions.php">
                        <select class="form-control" name="dates" required >
                            <option disabled> Please Select A Date </option>
                            <?php
                                //dates is array of dates
                                $dates = productAuctionDates();
                                //for every date produce every date in a drop down
                                foreach($dates as $date)
                                {
                                    echo '<option value="'.$date.'"> '.$date.' </option>';
                                }
                            ?>
                        </select>
                        <button class="btn btn-custom" name="auction-add" type="submit"> Create Auction </button>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body text-center">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h5 class="modal-title" id="exampleModalLabel text-center">Delete Confirmation</h5>
                        <p> Enter the Auction ID of the ID you want delete </p>
                        <form action="auctions.php" method="post">
                            <input class="mb-2" name="auctionID" type="number">
                            <br>
                            <button type="submit" class="btn  rounded-pill btn-custom" data-dismiss="modal"> <strong> No </strong> </button>
                            <button type="submit" class="btn  rounded-pill btn-custom" name="delete"><strong> Yes </strong></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>




    </div>
</div>
<?php require('Template/footer.phtml');?>
