<?php require('Template/header.phtml');?>
    <div class="container" >
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" style="margin: 220px;">
                <div class="card card-signin my-5 bg-light">
                    <div class="card-body" >
                        <h5 class="card-title text-center text-dark">LOG OUT</h5>
                        <form class="form-signin align-content-lg-center " method = "post" action = "logIn.php" >
                            <button name="logOutBtn" type="submit" class="btn mt-5 rounded-pill btn-lg btn-custom btn-block text-uppercase"  name="logOut">Log Out</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php require('Template/footer.phtml');?>