<?php require('Template/header.phtml'); ?>
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Register</h5>
                    <form class="form-signUp" action="register.php" method="post">
                        <div class="form-label-group">
                            <label for="inputPassword"><strong>Name:</strong></label>
                            <input type="text" name="name" class="form-control" placeholder="Name" required autofocus>
                        </div>
                        <div class="form-label-group">
                            <label for="inputPassword"><strong>Email address:</strong></label>
                            <input type="email" name="email1" class="form-control" placeholder="Email address" required>
                            <label for="inputPassword"><strong>Confirm Email address:</strong></label>
                            <input type="email" name="email2" class="form-control" placeholder="Confirm Email address"
                                   required>
                        </div>
                        <div class="form-label-group">
                            <label for="inputPassword"><strong>Password:</strong></label>
                            <input type="password" name="password1" class="form-control" placeholder="Password"
                                   required>
                            <label for="inputPassword"><strong>Confirm Password:</strong></label>
                            <input type="password" name="password2" class="form-control" placeholder="Confirm Password"
                                   required style="margin-bottom: 5px;">
                        </div>

                        <?php
                        //if both variables equal true after hitting the submit button then display a error message
                        if ($view->emailError == true && $view->passwordError == true) {
                            echo '<div class="alert alert-danger text-center" role="alert">
                            <i class="fa fa-exclamation-circle"> Email and Passwords do not match   </i>  
                        </div>';
                        }
                        //if the emails do not match when submit has been pressed display this error message
                        else if ($view->emailError == true) {
                            echo '<div class="alert alert-danger text-center" role="alert">
                            <i class="fa fa-exclamation-circle"> Emails do not match  </i>  
                        </div>';
                        }
                        //if the passwords do not match when submit has been pressed display this error message
                        else if ($view->passwordError == true) {
                            echo '<div class="alert alert-danger text-center" role="alert">
                            <i class="fa fa-exclamation-circle"> Passwords do not match   </i>  
                        </div>';
                        }
                        //if the email already exists then show an error
                        else if ($view->sameEmail == true) {
                            echo '<div class="alert alert-danger text-center" role="alert">
                            <i class="fa fa-exclamation-circle"> Email already exists  </i>  
                        </div>';
                        }
                        //if their is no errors show a success message
                        else if ($view->registered == true) {
                            echo '<div class="alert alert-success text-center" role="alert">
                            <i class="fa fa-check"> Successfully Registered! </i>  
                        </div>';
                        }
                        ?>
                        <button name="registerBtn" type="submit"
                                class="btn mt-5 rounded-pill btn-lg btn-custom btn-block text-uppercase">Register
                        </button>
                        <p class="mt-3 font-weight-normal text-center"> Already have a account? <a
                                    href="logIn.php"><strong> Log In Now</strong></a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php require('Template/footer.phtml'); ?>
