<?php require('Template/header.phtml'); ?>
<div class="container py-3" style="margin-bottom: 125px; margin-top: 125px">
    <?php
    // if the item has not been deleted then display the information else show the confirmation message
    if ($view->deleted == false) {
        echo '<h1 class="text-center">Auction For : ' . $view->productTitle . ' </h1>';
        echo '<div class="card" style="background: #414042; padding: 15px">
    <div class="row align-items-center ">';
        echo '<div class="col-md-4">
             <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
             
        <div class="carousel-inner">';

        //fetch all images returns an array and images is given this array which includes all of the image paths
        $images = fetchAllImages();

        $html = '<div class="carousel-item active">
      <img class="d-block w-100" src="%s">
    </div>';

        $html2 = '<div class="carousel-item">
      <img class="d-block w-100" src="%s">
    </div>';

        // a for each loop to produce each image in a carousel
        $i = 0;
        foreach ($images as $image) {
            if ($i == 0) {
                echo sprintf($html, $image);
            } else {
                echo sprintf($html2, $image);
            }
            $i++;
        }


        //a echo statement to print all details
        echo '</div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
        </div>
        <div class="col-md-8 px-3">
            <div class="card-block px-3">
                <h4 class="card-title text-white mt-2">Product Title : ' . $view->productTitle . '</h4>
                <h4 class="card-title text-white mt-2">Starting Bid : £' . $view->startingBid . '</h4>
                <h4 class="card-title text-white mt-2">Current Bid : £' . $view->currentBid . '</h4>
                 <h4 class="card-title text-white mt-2">StartDate : ' . $view->startDate . '</h4>
                <h4 class="card-title text-white mt-2">END DATE : ' . $view->endDate . '</h4>'; ?>
        <?php
        echo '<p class="card-text text-white"">Product Description: ' . $view->description . '</p>';

        $liveAuction = date("Y-m-d");
        //if an invalid bid is given show an error else show a success msg
        if ($view->invalidBid == true) {
            echo '<div class="alert alert-danger text-center" role="alert">
                            <i class="fa fa-exclamation-circle"> Please make sure you have entered a valid bid amount  </i>  
                        </div>';
        } else if ($view->validBid == true) {
            echo '<div class="alert alert-success text-center" role="alert">
                            <i class="fa fa-check"> Successfully Placed Your Bid </i>  
                        </div>';
        }
        echo '<form action="singleItem.php" method="post">';
        //if the user is admin then display a message
        if ($user->getAdminStatus() == true) {
            echo '<h4 class="card-title" style="color: red">You are admin</h4>';
            echo '<button name="dltbtn" type="button" class="btn  rounded-pill btn-custom  text-uppercase" data-toggle="modal" 
                       data-target="#exampleModal"> Delete </button>';
        }
        //if a user is not logged in display a message
        else if ($user->loggedIn() == false) {
            echo '<h4 class="card-title" style="color: red">Log in to bid on auctions</h4>';
        }
        //if the auction is not live and the current user is the owner show a delete button and display a message
        else if ($liveAuction != $view->startDate && $user->getUserID() == $view->userId) {
            echo '<h4 class="card-title" style="color: red"> Auction is not live</h4>';
            echo '<button name="dltbtn" type="button" class="btn  rounded-pill btn-custom  text-uppercase" data-toggle="modal" 
                       data-target="#exampleModal"> Delete </button>';
        }
        //if the auction is not live display a message
        else if ($liveAuction != $view->startDate) {
            echo '<h4 class="card-title" style="color: red">Auction is not live</h4>';
        }
        //if the auction is owned by the current user then let them see the bid button
        else if ($user->getUserID() != $view->userId) {
            echo '<input type="number" name="bidAmount" min="' . $view->leastAmount . '" ">
                <button type="submit" name="bidBtn" href="singleItem.php" class="btn btn-secondary my-2 my-sm-0 ">BID</button>
                </form>';
        } else {
            echo '<h4 class="card-title" style="color: red"> This is Your Auction</h4>';
            echo '<button name="dltbtn" type="button" class="btn  rounded-pill btn-custom  text-uppercase" data-toggle="modal" 
                       data-target="#exampleModal"> Delete </button>';
        }
        echo
        '</div>
        </div>';
    } else {
        echo '<h1 class="text-center text-dark" style="margin-bottom: 250px" >Auction Has been Deleted <a href="listedItems.php"> Click here to look at your listed items </a></h1>';
    }
    ?>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h5 class="modal-title" id="exampleModalLabel text-center">Delete Confirmation</h5>
                    <p> Are you sure you want to delete this auction? </p>
                    <form action="listedItems.php" method="post">
                        <button type="submit" class="btn  rounded-pill btn-custom" data-dismiss="modal"><strong>
                                No </strong></button>
                        <button type="submit" class="btn  rounded-pill btn-custom" name="delete"><strong> Yes </strong>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>


<?php require('Template/footer.phtml'); ?>
